### ISSUE TITLE
websocket: read limit exceeded

### ISSUE THREAD

**Issue by polariseye** [JFJun/go-substrate-rpc-client#3]
chain:ksm
blockIndex:8073545
由于区块数据过大导致websocket接收失败，需要把 github.com/JFJun/go-substrate-rpc-client/gethrpc/http.go中的maxRequestContentLength值扩大

**Comment by JFJun** [comment]
> chain:ksm
> blockIndex:8073545
> 由于区块数据过大导致websocket接收失败，需要把 github.com/JFJun/go-substrate-rpc-client/gethrpc/http.go中的maxRequestContentLength值扩大

好的，谢谢提的意见
